[WIP]am gov recipe
openstax/recipes pull request #15
Opened 2021-02-22 17:42 UTC by brittany-johnson

https://github.com/openstax/cnx-recipes/issues/3506

2021-06-03 21:10 UTC, LostMojo approved these changes
oooh, it's so _clean_

2021-06-04 15:07 UTC, kswanson33 requested changes
This needs specs! Look at chemistry, uphysics, and especially the documentation Karina's adding in the [calculus PR](https://github.com/openstax/recipes/pull/27/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R214-R231) for an example.

Aside from that, it looks good!

2021-06-04 15:21 UTC, jpslav requested changes

2021-06-04 15:21 UTC, jpslav commented on books/american_government/bake
> +  gem 'openstax_kitchen', ENV['USE_LOCAL_KITCHEN'] ? { path: '/code/kitchen' } : '2.0.0'
are you still using `2.0.0` locally?  If not, should update this to match.

2021-06-04 15:21 UTC, jpslav commented on books/american_government/bake
> +  book.chapters.pages.notes.each do |note|
do we need `chapters.pages` here?  can it be `book.notes`? Doesn't seem that `BakeUnclassifiedNotes` needs the chapter or page.

Actually, the latest interface of `BakeUnclassifiedNote` just takes the `book` and already includes the `note.classes.empty?` check -- can you upgrade and use that?

2021-06-04 15:21 UTC, jpslav commented on books/american_government/bake
> +    note.classes.empty? && BakeUnclassifiedNote.v1(note: note)
Generally speaking I'm not a big fan of this kind of use of `&&`.  Would rather change

```ruby
condition && thing_to_do
```

to

```ruby
thing_to_do if condition
```

reads better IMO

2021-06-22 19:02 UTC, kswanson33 approved these changes

2021-06-22 19:18 UTC, jpslav requested changes

2021-06-22 19:18 UTC, jpslav commented on books/american_government/bake
> +    chapter.search('.review-questions, .critical-thinking').exercises.each do |exercise|
Can these have the element name?  Element name searches are faster.  E.g. if they are always `div`...

```ruby
chapter.search(%w[review-questions critical-thinking].prefix('div.'))
```

Karina added the `prefix` method

... actually should have a line that is 

```ruby
exercise_section_classes = %w[review-questions critical-thinking]
```

and use that

```ruby
chapter.search(exercise_section_classes.prefix('div.'))
```

to help with below

2021-06-22 19:18 UTC, jpslav commented on books/american_government/bake
> +    )
Some repeated code here.  Consider replacing with

```ruby
exercise_section_classes.each do |klass|
  MoveExercisesToEOC.v1(chapter: chapter, metadata_source: metadata, klass: klass)
end
```

2021-06-22 19:18 UTC, jpslav commented on books/american_government/bake
> +      BakeNumberedTable.v1(table: table, number: "#{appendix_letter}#{table.count_in(:page)}", always_caption: true)
this line kinda long

2021-06-22 19:18 UTC, jpslav commented on books/american_government/bake
> +  end
does this `MoveSolutions...` call need to be here?  Can it instead be at the end of the other `book.chapters` loop above?

2021-06-22 22:23 UTC, jpslav approved these changes

2021-06-22 23:12 UTC, merged