Poli sci recipe
openstax/recipes pull request #46
Opened 2021-06-17 20:27 UTC by kswanson33

recipe for poli sci -- complete locally, but needs [Kitchen PR](https://github.com/openstax/kitchen/pull/280) to be merged & a new version released before it's ready

2021-07-08 19:20 UTC, LostMojo approved these changes

2021-07-12 19:13 UTC, kswanson33 commented
Profile run output -- this book is still in development, so this run is just on short test data & probably not very helpful

```
Search Profile Data
-----------------------------------------------------------------
Total Time (ms)  Avg Time (ms)  Count  Query
-----------------------------------------------------------------
1.3875           1.3875         1      //namespace::*
1.1144           1.1144         1      .//*[nokogiri-builtin:css-class(@class,'os-chapter-area')]
0.8616           0.8616         1      .//*[@data-type="cite"]
0.5353           0.5353         1      .//xmlns:div[@data-type='note']
1.0148           0.5074         2      .//xmlns:div[@data-type='metadata']
2.9314           0.4886         6      .//xmlns:div[@data-type='chapter']
0.4828           0.4828         1      .//xmlns:div[@data-type='page' and nokogiri-builtin:css-class(@class,'preface')]
0.9605           0.4802         2      .//xmlns:div[@data-type='composite-page']
0.4428           0.4428         1      .//xmlns:div[@data-type='unit']
1.5124           0.3781         4      .//xmlns:div[@data-type='page']
0.3742           0.3742         1      .//xmlns:div[@data-type="abstract"]
1.7818           0.3564         5      .//xmlns:div[@data-type='page' and not(nokogiri-builtin:css-class(@class,'introduction'))]
0.3434           0.3434         1      .//xmlns:div[@data-type='page' and nokogiri-builtin:css-class(@class,'introduction')]
0.6196           0.3098         2      .//xmlns:div[@data-type='glossary']
0.3033           0.3033         1      .//xmlns:table[not(nokogiri-builtin:css-class(@class,'unnumbered'))]
0.2818           0.2818         1      .//xmlns:nav
0.2711           0.2711         1      .//xmlns:a
2.0267           0.2533         8      .//*[nokogiri-builtin:css-class(@class,'reference')]
0.2338           0.2338         1      .//xmlns:figure[not(nokogiri-builtin:css-class(@class,'unnumbered'))]
0.2198           0.2198         1      .//xmlns:h1[count(preceding-sibling::*)=1]
0.1111           0.1111         1      .//xmlns:cnx-pi
0.1005           0.1005         1      .//xmlns:div[@data-type="description"] | .//xmlns:div[@data-type="abstract"]
0.3007           0.1002         3      .//xmlns:body
0.0841           0.0841         1      .//*[nokogiri-builtin:css-class(@class,'intro-text')]/*[@data-type='document-title']
0.5067           0.0724         7      .//xmlns:div[@data-type='description']
0.0534           0.0534         1      .//xmlns:div[@data-type='document-title']
0.6786           0.0522         13     .//xmlns:section[nokogiri-builtin:css-class(@class,'review-questions')]
0.5958           0.0496         12     .//xmlns:span[@data-type='term']
0.2568           0.0428         6      ./*[@data-type = 'document-title' or @data-type = 'title']
0.2519           0.0420         6      .//*[@data-type='revised']
0.2382           0.0397         6      .//xmlns:section[nokogiri-builtin:css-class(@class,'summary')]
0.5295           0.0378         14     .//xmlns:section[nokogiri-builtin:css-class(@class,'suggested-readings')]
0.2251           0.0375         6      .//*[nokogiri-builtin:css-class(@class,'print-style')]
0.2213           0.0369         6      .//xmlns:div[@data-type='exercise']
0.1948           0.0325         6      .//*[nokogiri-builtin:css-class(@class,'authors')]
0.1845           0.0308         6      .//*[nokogiri-builtin:css-class(@class,'publishers')]
0.1806           0.0301         6      .//*[nokogiri-builtin:css-class(@class,'permissions')]
0.0292           0.0292         1      ./*[not(@data-type='metadata') and not(nokogiri-builtin:css-class(@class,'splash')) and not(nokogiri-builtin:css-class(@class,'has-splash'))]
1.0895           0.0287         38     ./*[@data-type = 'document-title']
0.3321           0.0277         12     .//*[nokogiri-builtin:css-class(@class,'os-note-body')]
0.1880           0.0269         7      .//*[@data-type="title"]
0.1588           0.0265         6      .//*[@data-type='subject']
0.0237           0.0237         1      .//xmlns:span[@data-type='title']
0.3799           0.0211         18     .//*[@data-type='title']
0.2954           0.0211         14     .//*[nokogiri-builtin:css-class(@class,'os-part-text')]
0.1892           0.0210         9      .//*[nokogiri-builtin:css-class(@class,'os-text')]
0.2828           0.0202         14     .//*[nokogiri-builtin:css-class(@class,'os-number')]
0.0201           0.0201         1      .//xmlns:div[@data-type='abstract']
0.1201           0.0200         6      .//xmlns:dl
0.6232           0.0195         32     .//xmlns:div[@data-type='problem']
0.8124           0.0189         43     .//xmlns:dd
0.5553           0.0174         32     .//xmlns:div[@data-type='solution']
0.2283           0.0163         14     .//xmlns:div[@data-type='title']
0.0162           0.0162         1      .//xmlns:caption
0.2590           0.0162         16     /html/body/node()
0.2893           0.0161         18     ./*
0.6909           0.0161         43     .//xmlns:dt
0.0921           0.0154         6      .//xmlns:h3
0.2020           0.0144         14     .//xmlns:figcaption

Total time across all searches (ms): 29.290099999999995
Open:  0.0018686 s
Parse: 0.0137895 s
Bake:  0.3207171 s
Write: 0.0121555 s
```

2021-07-12 19:38 UTC, jpslav requested changes

2021-07-12 19:38 UTC, jpslav commented on books/political-science/bake
> +      append_to: chapter,
can remove this line, since it is the default?

2021-07-12 19:44 UTC, jpslav approved these changes

2021-07-12 19:44 UTC, merged