remove dummy tests
openstax/recipes pull request #93
Opened 2021-09-14 18:31 UTC by ckline-tryptic

2021-09-15 19:17 UTC, philschatz requested changes
It seems that the dummy test can still run by making the expected_output.xhtml be the same as input.xhtml

2021-09-27 15:23 UTC, philschatz approved these changes

2021-11-01 14:47 UTC, lwtchu commented
@ckline-tryptic @philschatz :eyes: is this still needed

2021-11-17 16:42 UTC, lwtchu commented
not sure if this was meant to be merged or closed...so we are closing. if we miss it we can reopen

2021-11-17 16:42 UTC, closed without merging